spring:
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.100.51.223:3306/forum?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: why19991009
      filter: stat
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 3600000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  level:
    studio.banner.forumwebsite: debug
    org.springfromework.web: info
    com.baomidou.mybatisplus: error
  mail:
    host: smtp.qq.com
    port: 587
    username: 2952434583@qq.com
    password: spmkmsoighssdhdd
    default-encoding: UTF-8
    properties:
      smtp:
        socketFactoryClass: javax.net.ssl.SSLSocketFactory
      debug: true
server:
  port: 8084

qiniu:
  path: qtga4eaxm.hn-bkt.clouddn.com
  accessKey: EeYNXo1hONmESybj2pe3YNBHO9Nar38Kf-QrbWEF
  secretKey: lpiYGtDzQP3M0xNx--WyAposkw6KLWSXvWsod1aO
  bucket: forumwebsite

#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: studio.banner.forumwebsite.bean


