spring:

  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://IP/database?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: ******
      password: ******
      filter: stat
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 3600000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  level:
    studio.banner.forumwebsite: debug
    org.springfromework.web: info
    com.baomidou.mybatisplus: error
  # 上传文件大小
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  #redis
  redis:
    host: IP
    port: port
    database: 0
    password: ******
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0
#    mongodb
  data:
    mongodb:
      uri: mongodb://IP/database

  mvc:
    view:
      suffix: .html
      prefix: /html/
#    es全文检索
  elasticsearch:
    rest:
      uris: IP:host
      read-timeout: 30s
      connection-timeout: 5s
  #  邮箱
  mail:
    host: smtp.qq.com
    port: 587
    username: email@qq.com
    password: spmkmsoighssdhdd
    default-encoding: UTF-8
    properties:
      smtp:
        socketFactoryClass: javax.net.ssl.SSLSocketFactory
      debug: true

  devtools:
    restart:
#      关闭热部署
      enabled: false
#      不参与热部署
      exclude: static/**,templates/**
server:
  port: 8084

# 腾讯云地址
qcloud:
  path: https://ljxlwyq-1308186257.cos.ap-beijing.myqcloud.com
  bucketName: ljxlwyq-1308186257
  secretId: *****
  secretKey: *****
  region: ap-beijing
  prefix: /images/


#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: studio.banner.forumwebsite.bean

